name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      NODE_OPTIONS: --max-old-space-size=8192

      STUDIO_GITHUB_CLIENT_SECRET: ${{ secrets.STUDIO_GITHUB_CLIENT_SECRET }}
      STUDIO_GITHUB_CLIENT_ID: ${{ vars.STUDIO_GITHUB_CLIENT_ID }}

      NITRO_PRESET: ${{ vars.NITRO_PRESET }}

      NUXT_PUBLIC_SUPABASE_KEY: ${{ vars.NUXT_PUBLIC_SUPABASE_KEY }}
      NUXT_PUBLIC_SUPABASE_URL: ${{ vars.NUXT_PUBLIC_SUPABASE_URL }}

      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      SUPABASE_GOOGLE_CLIENT_ID: ${{ secrets.SUPABASE_GOOGLE_CLIENT_ID }}
      SUPABASE_GOOGLE_SECRET: ${{ secrets.SUPABASE_GOOGLE_SECRET }}

      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}

      NUXT_HUB_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      NUXT_HUB_CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
      NUXT_HUB_CLOUDFLARE_DATABASE_ID: ${{ vars.CLOUDFLARE_DATABASE_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0

      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.6
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: migrate db
        if: github.ref_name == 'main'
        run: npx wrangler d1 migrations apply nuxt-frigear-nu --remote
#        run: pnpm db:migrate

      - name: deploy to production
        if: github.ref_name == 'main'
        run: pnpm cf:deploy
